bitbag_sylius_wishlist_plugin_shop_no_prefix:
  resource: "@BitBagSyliusWishlistPlugin/Resources/config/routing/shop.yml"
  name_prefix: 'bitbag_sylius_wishlist_plugin_shop_'

bitbag_sylius_wishlist_plugin_shop:
  resource: "@BitBagSyliusWishlistPlugin/Resources/config/routing/shop.yml"
  name_prefix: 'bitbag_sylius_wishlist_plugin_shop_locale_'
  prefix: /{_locale}
  requirements:
    _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

bitbag_sylius_wishlist_plugin_admin:
  resource: |
    alias: bitbag_plugin_wishlist.wishlist
    section: admin
    templates: "@SyliusAdmin\\Crud"
    redirect: update
    grid: bitbag_wishlist
    vars:
        all:
            subheader: app.ui.supplier
        index:
            icon: 'file image outline'
  type: sylius.resource
  prefix: /admin
